feature:
  - any: ["src/**/*"]

tests:
  - any: ["tests/**/*"]

config:
  - any: ["*"]

devops:
  - any: [".github/**/*"]

client:
  - any: ["src/pages/**/*", "src/components/**/*"]

server:
  - any: ["src/server/**/*", "src/components/**/*"]
