feature:
  - all:
      - changed-files:
          - any-glob-to-any-file: ["src/**/*"]
          - all-globs-to-all-files: ["!tests/**/*"]

tests:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["tests/**/*"]

config:
  - all:
      - changed-files:
          - any-glob-to-any-file: ["*"]
          - all-globs-to-all-files:
              ["!package.json", "!pnpm-lock.yaml", "!README.md"]

devops:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/**/*"]

frontend:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["src/app/**/*", "src/components/**/*"]

backend:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["src/server/**/*", "src/utils/**/*"]

scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["scripts/**/*"]
