feature:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["src/**/*"]

tests:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["tests/**/*"]

config:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["*"]
          - all-globs-to-all-files: ["!package.json"]

devops:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/**/*"]

client:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["src/pages/**/*", "src/components/**/*"]

server:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["src/server/**/*", "src/utils/**/*"]

scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["scripts/**/*"]
