feature:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["src/**/*"]

tests:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["tests/**/*"]

config:
  - all:
      - changed-files:
          - any-glob-to-any-file: ["*"]
          - all-globs-to-all-files: ["!pnpm-lock.yaml"]

devops:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/**/*"]

frontend:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["src/pages/**/*", "src/components/**/*"]

backend:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["src/server/**/*", "src/utils/**/*"]

scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["scripts/**/*"]
