services:
  test-db:
    image: postgres:15-alpine
    container_name: pokezoo-test-db
    environment:
      POSTGRES_DB: pokezoo_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d pokezoo_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_db_data:
