import { db } from "~/server/db";
import { species } from "~/server/db/schema";

const paldeanForms = async () => {
  await db.insert(species).values([
    {
      pokedexNumber: 194,
      name: "wooper-paldea",
      rarityId: 1,
      yield: 10,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10253.png",
      sellPrice: 50,
      shiny: false,
      typeOneId: 9,
      typeTwoId: 6,
      generation: 9,
      habitatId: 3,
      regionId: 10,
    },
    {
      pokedexNumber: 194,
      name: "wooper-paldea",
      rarityId: 1,
      yield: 20,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10253.png",
      sellPrice: 100,
      shiny: true,
      typeOneId: 9,
      typeTwoId: 6,
      generation: 9,
      habitatId: 3,
      regionId: 10,
    },
    {
      pokedexNumber: 128,
      name: "tauros-paldea-combat-breed",
      rarityId: 3,
      yield: 300,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10250.png",
      sellPrice: 1500,
      shiny: false,
      typeOneId: 8,
      typeTwoId: null,
      generation: 9,
      habitatId: 1,
      regionId: 10,
    },
    {
      pokedexNumber: 128,
      name: "tauros-paldea-combat-breed",
      rarityId: 3,
      yield: 600,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10250.png",
      sellPrice: 3000,
      shiny: true,
      typeOneId: 8,
      typeTwoId: null,
      generation: 9,
      habitatId: 1,
      regionId: 10,
    },
    {
      pokedexNumber: 128,
      name: "tauros-paldea-blaze-breed",
      rarityId: 3,
      yield: 300,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10251.png",
      sellPrice: 1500,
      shiny: false,
      typeOneId: 8,
      typeTwoId: 4,
      generation: 9,
      habitatId: 1,
      regionId: 10,
    },
    {
      pokedexNumber: 128,
      name: "tauros-paldea-blaze-breed",
      rarityId: 3,
      yield: 600,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10251.png",
      sellPrice: 3000,
      shiny: true,
      typeOneId: 8,
      typeTwoId: 4,
      generation: 9,
      habitatId: 1,
      regionId: 10,
    },
    {
      pokedexNumber: 128,
      name: "tauros-paldea-aqua-breed",
      rarityId: 3,
      yield: 300,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10252.png",
      sellPrice: 1500,
      shiny: false,
      typeOneId: 8,
      typeTwoId: 4,
      generation: 7,
      habitatId: 1,
      regionId: 10,
    },
    {
      pokedexNumber: 128,
      name: "tauros-paldea-aqua-breed",
      rarityId: 3,
      yield: 600,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10252.png",
      sellPrice: 3000,
      shiny: true,
      typeOneId: 8,
      typeTwoId: 4,
      generation: 7,
      habitatId: 1,
      regionId: 10,
    },
    {
      pokedexNumber: 999,
      name: "gimmighoul-roaming",
      rarityId: 3,
      yield: 300,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10263.png",
      sellPrice: 1500,
      shiny: false,
      typeOneId: 12,
      typeTwoId: null,
      generation: 9,
      habitatId: 8,
      regionId: 10,
    },
    {
      pokedexNumber: 999,
      name: "gimmighoul-roaming",
      rarityId: 3,
      yield: 600,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10263.png",
      sellPrice: 3000,
      shiny: true,
      typeOneId: 12,
      typeTwoId: null,
      generation: 9,
      habitatId: 8,
      regionId: 10,
    },
    {
      pokedexNumber: 1017,
      name: "ogerpon-wellspring-mask",
      rarityId: 4,
      yield: 1000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10273.png",
      sellPrice: 5000,
      shiny: false,
      typeOneId: 2,
      typeTwoId: 7,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1017,
      name: "ogerpon-wellspring-mask",
      rarityId: 4,
      yield: 2000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10273.png",
      sellPrice: 10000,
      shiny: true,
      typeOneId: 2,
      typeTwoId: 7,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1017,
      name: "ogerpon-hearthflame-mask",
      rarityId: 4,
      yield: 1000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10274.png",
      sellPrice: 5000,
      shiny: false,
      typeOneId: 2,
      typeTwoId: 4,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1017,
      name: "ogerpon-hearthflame-mask",
      rarityId: 4,
      yield: 2000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10274.png",
      sellPrice: 10000,
      shiny: true,
      typeOneId: 2,
      typeTwoId: 4,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1017,
      name: "ogerpon-cornerstone-mask",
      rarityId: 4,
      yield: 1000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10275.png",
      sellPrice: 5000,
      shiny: false,
      typeOneId: 2,
      typeTwoId: 10,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1017,
      name: "ogerpon-cornerstone-mask",
      rarityId: 4,
      yield: 2000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10275.png",
      sellPrice: 10000,
      shiny: true,
      typeOneId: 2,
      typeTwoId: 10,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1024,
      name: "terapagos-terastal",
      rarityId: 4,
      yield: 1000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10276.png",
      sellPrice: 5000,
      shiny: false,
      typeOneId: 1,
      typeTwoId: null,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1024,
      name: "terapagos-terastal",
      rarityId: 4,
      yield: 2000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10276.png",
      sellPrice: 10000,
      shiny: true,
      typeOneId: 1,
      typeTwoId: null,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1024,
      name: "terapagos-stellar",
      rarityId: 4,
      yield: 1000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10277.png",
      sellPrice: 5000,
      shiny: false,
      typeOneId: 1,
      typeTwoId: null,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
    {
      pokedexNumber: 1024,
      name: "terapagos-stellar",
      rarityId: 4,
      yield: 2000,
      img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10277.png",
      sellPrice: 10000,
      shiny: true,
      typeOneId: 1,
      typeTwoId: null,
      generation: 9,
      habitatId: 9,
      regionId: 10,
    },
  ]);

  console.log("done!");
};

void paldeanForms();
