name: Update User Dollars Cron
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: cron job
        run: "curl -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{ secrets.CRON_TOKEN }}' -X POST https://pokezoo.vercel.app/api/cron"
