name: Update User Dollars Cron
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: cron job
        run: |
          curl -H "Content-Type: application/json" \ 
          -H "Authorization: Bearer ${{secrets.CRON_TOKEN }}" \
          -X POST \
          localhost:3000/api/cron
