name: Playwright Tests

on:
  push:
    branches: [main, master]
    # Skip CI for documentation changes
    paths-ignore:
      - "**/*.md"
      - "**/*.mdx"
      - "**/docs/**"
jobs:
  e2e:
    name: Run E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # This allows a single in-progress job to be canceled when a new commit is pushed
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          GREEN_SESSION: ${{ secrets.GREEN_SESSION }}
          RED_SESSION: ${{ secrets.RED_SESSION }}
          BLUE_SESSION: ${{ secrets.BLUE_SESSION }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          NODE_ENV: "production"
          SKIP_VALIDATION: "true"
          AUTH_TRUST_HOST: "true"
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
