name: Playwright Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    concurrency:
      group: test-group
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        env:
          NODE_ENV: "test"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          GREEN_SESSION: ${{ secrets.GREEN_SESSION }}
          RED_SESSION: ${{ secrets.RED_SESSION }}
          BLUE_SESSION: ${{ secrets.BLUE_SESSION }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          SKIP_VALIDATION: "true"
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
