name: Playwright Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm ci
      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps
      - name: Run Playwright tests
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          TEST_NAME: ${{ secrets.TEST_NAME }}
          TEST_VALUE1: ${{ secrets.TEST_VALUE1 }}
          TEST_UNAME1: ${{ secrets.TEST_UNAME1 }}
          TEST_VALUE2: ${{ secrets.TEST_VALUE2 }}
          TEST_UNAME2: ${{ secrets.TEST_UNAME2 }}
          TEST_RESET: ${{ secrets.TEST_RESET  }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL}}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN}}
          SKIP_VALIDATION: "true"
        run: pnpm dlx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
